spring:
  application:
    name: hexaceps
  datasource:
    url: jdbc:h2:tcp://localhost/~/devtest # testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update   #create  update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-request-size : 30MB # transfer data per one-time
      max-file-size : 10MB # size of one file
  security:
    user:
      name: user
      password: 1111


org:
  zerock:
    upload:
      path: upload # file saved in project folder created name by upload

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.security.web: trace
server:
  port: 8050
